// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0d1hHOHQABUk-3R9CKLN-W9dMefkF6jE',
    appId: '1:917182420756:web:1ddaf3ea629c254adad401',
    messagingSenderId: '917182420756',
    projectId: 'e-commerce-baec5',
    authDomain: 'e-commerce-baec5.firebaseapp.com',
    storageBucket: 'e-commerce-baec5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASWz5uLaUD8ILp18Z_EKt6skjNe4IwIpI',
    appId: '1:917182420756:android:16c64506f704c0dfdad401',
    messagingSenderId: '917182420756',
    projectId: 'e-commerce-baec5',
    storageBucket: 'e-commerce-baec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0nsW5caRiaO1vQgGo-AQtUGjRrocNP4I',
    appId: '1:917182420756:ios:a7310462480be74bdad401',
    messagingSenderId: '917182420756',
    projectId: 'e-commerce-baec5',
    storageBucket: 'e-commerce-baec5.appspot.com',
    iosClientId: '917182420756-6423pmhth8ombt1atq2u0s7gk1143g3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
